version: "3.6"

services:
  tag_searcher:
    image: tag_searcher
    build:
      context: .
      dockerfile: config/docker/Dockerfile.tag_searcher
    environment:
     - PYTHONUNBUFFERED=0
    volumes:
      - ./:/app/
    ports:
      - "2000:2000"
    networks:
      main:
        aliases:
          - tag_searcher
    command: [
      "python3.6",
      "-m",
      "tag_searcher",
      "--port",
      "2000",
      "--host",
      "0.0.0.0"
    ]

  pytest:
    image: tag_searcher
    build:
      context: .
      dockerfile: config/docker/Dockerfile.tag_searcher
    environment:
     - PYTHONUNBUFFERED=0
    volumes:
      - ./:/app/
    networks:
      main:
        aliases:
          - pytest
    command: [
      "pytest",
      "tests"
    ]

networks:
  main:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/16
