FROM python:3.6.7-slim as tag_searcher

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    g++ \
    make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ADD ./requirements /app/requirements
ADD ./tag_searcher /app/tag_searcher

RUN pip3 install -r requirements/requirements.txt
